[package]
name = "timezone-dispatch"
version = "0.1.0"
authors = ["jude-LafiteIII <judewrs@gmail.com>"]

[dependencies]
mysql = "14.2"
dotenv = "0.10.1"
chrono = "0.4"
chrono-tz = "0.4"
reqwest = "0.9.5"
threadpool = "1.7.1"
